apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rocketchat-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/zaverous/rocketchat.git'
    path: Deployment
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: rocketchat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
